Changed Cmake files
arfc/cyder pull request #13
Opened 2018-04-02 20:28 UTC by gwenchee

Added CMakeLists.txt file, Added install.py file , Changed src/CMakeLists.txt file 
So that they correspond with cyclus/stubs folder 

Also, renamed all cpp files to cc.

2018-04-02 20:28 UTC, pep8speaks commented
Hello @gwenchee! Thanks for submitting the PR.

 - In the file [`install.py`](https://github.com/arfc/cyder/blob/7ee491f921e12b74dde99283b4e81211d508d993/install.py), following are the PEP8 issues :

> [Line 12:1](https://github.com/arfc/cyder/blob/7ee491f921e12b74dde99283b4e81211d508d993/install.py#L12): [E731](https://duckduckgo.com/?q=pep8%20E731) do not assign a lambda expression, use a def
> [Line 78:1](https://github.com/arfc/cyder/blob/7ee491f921e12b74dde99283b4e81211d508d993/install.py#L78): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 97:80](https://github.com/arfc/cyder/blob/7ee491f921e12b74dde99283b4e81211d508d993/install.py#L97): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 118:40](https://github.com/arfc/cyder/blob/7ee491f921e12b74dde99283b4e81211d508d993/install.py#L118): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 136:1](https://github.com/arfc/cyder/blob/7ee491f921e12b74dde99283b4e81211d508d993/install.py#L136): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 137:11](https://github.com/arfc/cyder/blob/7ee491f921e12b74dde99283b4e81211d508d993/install.py#L137): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2018-04-09 19:44 UTC, katyhuff requested changes
Minor comments.

2018-04-09 19:44 UTC, katyhuff commented on src/CMakeLists.txt
> +# USE_CYCLUS("cyder" "NuclideModel")
Why is this different from the others?
Anyway, if you want to delete the line, just delete this line. No  need to keep it around as a comment.

2018-04-09 19:44 UTC, katyhuff commented on src/CMakeLists.txt
> +# should i include for header files that do not have cc files?
I don't understand this question. In any case, it shouldn't be a comment in committed code. This is the kind of thing that should be an open issue (it's a question, it can be solved with a compatible pull request).

2018-04-09 19:44 UTC, katyhuff commented on install.py
> +#! /usr/bin/env python
I think this file is technically under the cyclus (or cycamore?) BSD-3 license and should therefore be attributed (attribution is one of the three clauses.). Ideally, it and its history should be merged in and committed here, rather than just copy-pasting the code into this repository. If you choose to do the latter, then you can attribute the source with a comment near/at the top of the file.

2018-04-09 19:46 UTC, gwenchee commented on src/CMakeLists.txt
> +# USE_CYCLUS("cyder" "NuclideModel")
I'm not sure if i should include it or not because that folder lacks a cc file and so it is throwing an error when i run python install.py

2018-05-14 18:05 UTC, merged