Packagedmaterial
arfc/cyder pull request #57
Opened 2019-01-03 17:26 UTC by gwenchee

This PR contains 
1) Conditioning Facility 
2) Packaged Material Sink Facility 
3) simple_test.xml test file that provides a simplest working scenario for the conditioning and trading of a packaged material resource

2019-02-13 17:41 UTC, gwenchee commented
It runs with https://github.com/gwenchee/cyclus/tree/packaged-material branch of Cyclus

2019-02-13 18:13 UTC, gtw2 reviewed
Looks pretty clean, found a couple things to clarify/fix.

2019-02-13 18:13 UTC, gtw2 commented on src/conditioning.h
> +                     "doc":"the max number of waste canisters that can be moved through the facility per timestep",\
Is this the maximum physical throughput for the facility, or throughput for a given simulation?

2019-02-13 18:13 UTC, gtw2 commented on src/pmstorage.cc
> +} // namespace pmstorage
Should be a blank line here, missing commit?
```suggestion
} // namespace pmstorage

```

2019-02-15 22:06 UTC, katyhuff requested changes

2019-02-15 22:06 UTC, katyhuff commented on .gitignore
> +*.sh
why ignore bash scripts? (if this is for more comfortable use of `git add *`, please stop using `git add *` and transition to `git add ONCE && git commit -am "... "`)

2019-02-15 22:06 UTC, katyhuff commented on src/conditioning.cc
> +  PackageMatl_(package_size,package_properties);
```suggestion
  PackageMatl_(package_size, package_properties);
```

2019-02-15 22:06 UTC, katyhuff commented on src/conditioning.cc
> +typedef std::map<std::string, std::map<std::string, double>> package_;
If "package" gets any more complex than this, it maybe should be a struct, or its own class...

2019-02-15 22:06 UTC, katyhuff commented on src/conditioning.cc
> +    // create a new packagedmaterial
This comment (as well as some other comments) feels a little superfluous. It's up to you, but I'll just leave this here for you to consider:

http://www.informit.com/articles/article.aspx?p=1326509

2019-02-15 22:06 UTC, katyhuff commented on src/conditioning.cc
> +        cap_pop = cap_pop+1;
It might be wise to have test double checking that you don't have any off-by-one errors in this little segment.

2019-02-15 22:06 UTC, katyhuff commented on src/conditioning.h
> +  void PackageMatl_(int size_package,std::map<std::string, std::map<std::string, double>> package_properties);
is this line over the max line length?

2019-02-15 22:06 UTC, katyhuff commented on src/conditioning.h
> +  void PackageMatl_(int size_package,std::map<std::string, std::map<std::string, double>> package_properties);
also, spaces after commas in the param list... 
```suggestion
  void PackageMatl_(int size_package, std::map<std::string, std::map<std::string, double>> package_properties);
```

2019-02-15 22:06 UTC, katyhuff commented on src/conditioning.h
>    /// @param *** ADD HERE ***
needs documentation.

2019-02-15 22:06 UTC, katyhuff commented on src/conditioning.h
> +                     "doc":"the max number of waste canisters that can be moved through the facility per timestep",\
max line length?

2019-02-15 22:06 UTC, katyhuff commented on src/pmsink.h
> +    " material with that recipe. Requests are made for any number of\n"\
Is this true, does it request materials with a specific recipe if a recipe is provided?

2019-02-15 22:06 UTC, katyhuff commented on src/pmsink.h
> +
Too many blank lines.

2019-02-15 22:06 UTC, katyhuff commented on src/pmsink.h
> +  /// resource type!
Rather than an exclamation mark, consider the "\warning" doxygen syntax. http://www.doxygen.nl/manual/commands.html#cmdwarning

Related... are you trying to say something like.. do/dont use this function? what is the purpose of noting this? why should the user be concerned? (real question, not rhetorical, please respond)

2019-02-15 22:06 UTC, katyhuff commented on src/pmsink.h
> +  /// resource type!
Rather than an exclamation mark, consider the "\warning" doxygen syntax. http://www.doxygen.nl/manual/commands.html#cmdwarning

2019-02-15 22:06 UTC, katyhuff commented on src/pmsink.h
> +  ///  @param name the commodity name
it helps to point out the parameter type (string)

2019-02-15 22:06 UTC, katyhuff commented on src/pmsink.h
> +  ///  @param size the storage size
it helps to point out the parameter type (double) and units (kg? number of packages?)

2019-02-15 22:06 UTC, katyhuff commented on src/pmsink.h
> +  /// @param capacity the reception capacity
it helps to point out the parameter type (double) and units (kg? number of packages?)

2019-02-15 22:06 UTC, katyhuff commented on src/pmstorage.h
> +/// max_inv_size is the maximum capacity of the inventory pmstorage
units?

2019-02-15 22:06 UTC, katyhuff commented on src/pmstorage.h
> +/// throughput is the maximum processing capacity per timestep
units?

2019-02-15 22:06 UTC, katyhuff commented on src/pmstorage.h
> +/// Nothing really happens on the tick.
surely something?

2019-02-15 22:06 UTC, katyhuff commented on src/pmstorage.h
> +  /// @param cap current throughput capacity
it helps to point out the parameter type (double) and units (kg? number of packages?)

2019-02-15 22:06 UTC, katyhuff commented on src/pmstorage.h
> +  /// @param time the time of interest
```suggestion
  /// @param time the timestep of interest
```

2019-02-15 22:06 UTC, katyhuff commented on src/pmstorage.h
> +  /// @brief current maximum amount that can be added to processing
units?

2019-02-15 22:06 UTC, katyhuff commented on src/pmstorage.h
> +  /// @brief returns the time key for ready materials
what is a time key?

2019-02-17 21:09 UTC, gwenchee commented on src/conditioning.h
> +                     "doc":"the max number of waste canisters that can be moved through the facility per timestep",\
It is the maximum physical throughput for the facility

2019-02-17 21:13 UTC, gwenchee commented on .gitignore
> +*.sh
yup will do that from now on

2019-02-17 21:23 UTC, gwenchee commented on src/pmsink.h
> +  /// resource type!
Pmsink is copied from the sink facility in cycamore. The documentation is actually from there. I suppose it should be updated.

2019-02-17 21:31 UTC, gwenchee commented on src/pmstorage.h
> +/// Nothing really happens on the tick.
leftover documentation again from the cycamore storage facility

2019-02-17 21:41 UTC, gwenchee commented on src/conditioning.cc
> +    // create a new packagedmaterial
thats true.. i might leave in the comments for now, since it is helpful to me still

2025-03-18 19:47 UTC, merged